/**
 * 表格族页面构建器（源 core/image/{update_table,rating_table,plate_table}.py 坐标直译）
 * 视觉设计派生自 nonebot-plugin-maimaidx（Yuri-YuzuChaN）及上游 mai-bot。
 *
 * ADR-7：源把这两页叠在 `更新定数表`/`更新完成表` 命令**运行时预生成**的整页底图上，
 * 那批 PNG 是本机产物、不在上游资源包内 —— 本模块按源生成器（update_table.py）**同一套坐标**
 * 在 HTML/CSS 侧重画底图（渐变 + 毛玻璃卡 + 曲绘网格），再叠用户相关层。
 * 布局算术全部来自 lib/tableLayout.js，本文件只负责「按源的调用顺序产出渲染元素」。
 *
 * ⚠️ z 阶梯（比源多出来的唯一一处显式建模）：PIL 严格按调用序叠层，而 CSS 需要显式 z；
 * 且 complete_1/unfinished_1/complete_2 是**半透明**（实测 maxA=179）并压在底图曲 id 文字之上，
 * 压错层不是轻微色偏而是每个已游玩格一片 hard 格。故统一：装饰 0 / 卡片 1 / 网格图 2 /
 * 底图文字 3 / 叠加贴图 4 / 叠加文字 5 / 逐格状态 6。
 */
import fs from 'node:fs'
import {
  img, txt, picSrc, themedPicSrc, maiSrc, songChartSrc, tricolorGradientCss,
  DIFF_TEXT_COLOR, DIFF_BG_NAMES, DEFAULT_TEXT_COLOR, ID_TEXT_COLOR,
} from './views.js'
import { pyRound2 } from './textwidth.js'
import { ratingTableLayout, level15Layout, plateTableLayout, RATING_GRID } from '../tableLayout.js'
import { calcAchievementsFc, PLAN_CRITERIA } from '../tableData.js'
import { computeRating } from '../calc.js'
import { COMBO_MAP, COMBO_SP, RANK_MAP, RANK_SP, STATISTICS_KEYS, SYNC_MAP } from '../constants.js'

/** z 阶梯（见文件头注释，勿逐页自创） */
export const Z = { DECO: 0, CARD: 1, GRID_IMG: 2, BASE_TEXT: 3, OV_ART: 4, OV_TEXT: 5, CELL: 6 }

/** 源 AssetsImage._font_color = (114,188,254,255)（表格族统一字色） */
const FONT_COLOR = '#72bcfe'

/** 源 generate_frosted_card 默认参数；表格卡面积远大于 songlist 卡，alpha 需按页标定（见 B4） */
export const FROSTED = {
  radius: 25, alpha: 0.4, blur: 4,
  shadow: '10px 10px 12px rgba(0, 0, 0, 0.20)',
}

/**
 * 源 update_table.py:_generate_bg —— 装饰底（渐变由 CSS 承担，其余为按坐标铺的贴图）
 * @param {number} height 源坐标空间高度
 * @param {number|null} separatorHeight separator.png 的 y（定数表 360 / 完成表 400）；null 不画
 */
export function tableBgLayers(height, separatorHeight = null) {
  const images = [
    img(picSrc('aurora.png'), 0, 0, null, null, { z: Z.DECO }),
    img(picSrc('bg_shines.png'), 11, 6, null, null, { z: Z.DECO }),
    img(picSrc('rainbow.png'), 318, height - 545, null, null, { z: Z.DECO }),
    img(picSrc('rainbow_bottom.png'), 122, height - 305, null, null, { z: Z.DECO }),
  ]
  // 源 for h in range(height // 358 + 1): pattern 落在 (0, (358+7)*h)
  for (let h = 0; h <= Math.floor(height / 358); h++) {
    images.push(img(picSrc('pattern.png'), 0, 365 * h, null, null, { z: Z.DECO }))
  }
  if (separatorHeight !== null) {
    images.push(img(picSrc('separator.png'), 100, separatorHeight, null, null, { z: Z.DECO }))
  }
  return images
}

/** 源 generate_frosted_card 的卡片数据（含属性，模板只负责打印） */
export function cardElement(card) {
  return { ...card, ...FROSTED, z: Z.CARD }
}

/** 源页脚 `Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {bot_name} BOT` */
export function footerElement(footer, botName) {
  return txt(
    `Designed by Yuri-YuzuChaN & BlueDeer233. Generated by ${botName} BOT`,
    footer.x, footer.y, 30,
    { font: 'fot', color: FONT_COLOR, anchor: 'mm', z: Z.BASE_TEXT }
  )
}

/**
 * 定数表底图（源 update_table.py:121 的绘制部分）
 * @param {object} layout lib/tableLayout.js 的 ratingTableLayout 输出
 * @param {string} botName
 */
function ratingBaseLayers(layout, botName) {
  const images = tableBgLayers(layout.height, layout.separatorHeight)
  const texts = []
  for (const g of layout.groups) {
    // 源 fot.draw(70, START_Y + 35, 40, f".{ds.split('.')[-1]}", ..., lm, stroke 4 white)
    texts.push(txt(`.${g.ds.split('.')[1]}`, g.labelX, g.labelY, 40,
      { font: 'fot', color: FONT_COLOR, anchor: 'lm', stroke: 4, strokeColor: '#ffffff', z: Z.BASE_TEXT }))
    for (const cell of g.songs) {
      const li = cell.song.difficulties.level_index
      images.push(img(songChartSrc(cell.song.song_id), cell.x, cell.y, 75, 75, { z: Z.GRID_IMG }))
      // 难度边框压在曲绘之上（源先 composite cover 再 composite border）
      images.push(img(picSrc(`border_${DIFF_BG_NAMES[li]}.png`), cell.x - 5, cell.y - 5, null, null, { z: Z.GRID_IMG }))
      texts.push(txt(cell.song.song_id, cell.x + 56, cell.y + 4, 13,
        { font: 'tb', color: DIFF_TEXT_COLOR[li], anchor: 'mm', z: Z.BASE_TEXT }))
    }
  }
  texts.push(footerElement(layout.footer, botName))
  return { images, texts }
}

/** 等级 15 定数表底图（源 update_table.py:63 的绘制部分） */
function level15BaseLayers(layout, botName) {
  const images = tableBgLayers(layout.height, layout.separatorHeight)
  const texts = []
  for (const cell of layout.cells) {
    images.push(img(picSrc('chart_white.png'), cell.x, cell.y, null, null, { z: Z.GRID_IMG }))
    if (cell.song) {
      images.push(img(songChartSrc(cell.song.song_id), cell.x + 10, cell.y + 10, 330, 330, { z: Z.GRID_IMG }))
      images.push(img(picSrc(`${cell.song.type}.png`), cell.x + 200, cell.y + 345, null, null, { z: Z.GRID_IMG }))
      images.push(img(picSrc(`${cell.song.version_str}.png`), cell.x + 9, cell.y - 80, 332, 160, { z: Z.GRID_IMG }))
      texts.push(txt(cell.song.song_id, cell.x + 100, cell.y + 370, 35,
        { font: 'fot', color: FONT_COLOR, anchor: 'mm', z: Z.BASE_TEXT }))
    } else {
      // 源占位格：song_chart(0) + DX 徽标 + 「????」无描边 + 「UNKNOWN」8px 白描边
      images.push(img(songChartSrc(0), cell.x + 10, cell.y + 10, 330, 330, { z: Z.GRID_IMG }))
      images.push(img(picSrc('DX.png'), cell.x + 200, cell.y + 345, null, null, { z: Z.GRID_IMG }))
      texts.push(txt('????', cell.x + 100, cell.y + 370, 35,
        { font: 'fot', color: FONT_COLOR, anchor: 'mm', z: Z.BASE_TEXT }))
      texts.push(txt('UNKNOWN', cell.x + 175, cell.y + 280, 30,
        { font: 'fot', color: FONT_COLOR, anchor: 'mm', stroke: 8, strokeColor: '#ffffff', z: Z.BASE_TEXT }))
    }
  }
  texts.push(footerElement(layout.footer, botName))
  return { images, texts }
}

/**
 * 定数表 / 定数完成表页面（源 core/image/rating_table.py:153 DrawRatingTable.draw）
 *
 * levelText=true  → 源 `定数表` 指令：仅叠 `Level.` + 定数两行字，**不缩放**（输出 1400 宽）。
 * levelText=false → 源「完成表」：叠统计行、complete.png 与逐格状态，**整图 ×0.8**（输出 1120 宽）。
 *
 * @param {object} opts
 * @param {string} opts.rating 定数字面（"13" / "13+"）
 * @param {object} opts.levelData mai.totalLevelData[rating]
 * @param {boolean} [opts.levelText] true=纯定数表标题模式
 * @param {boolean} [opts.plan] 完成表 fc/ap 计划模式
 * @param {Record<string, number>} [opts.statistics] processRatingTableData 输出
 * @param {Map} [opts.playedMap] processRatingTableData 输出
 * @param {string} opts.botName
 */
export function ratingTableView({
  rating, levelData, levelText = false, plan = false,
  statistics = null, playedMap = null, botName = '',
}) {
  const isLv15 = rating === '15'
  const layout = isLv15 ? level15Layout(levelData?.['15.0']) : ratingTableLayout(levelData)
  const base = isLv15 ? level15BaseLayers(layout, botName) : ratingBaseLayers(layout, botName)
  const images = base.images
  const texts = base.texts

  // 源 level_text 分支：y=220；全分支：y=160（两者均 anchor ld、fot、stroke 8 白）
  const titleY = levelText ? 220 : 160
  texts.push(txt('Level.', 495, titleY, 70,
    { font: 'fot', color: FONT_COLOR, anchor: 'ld', stroke: 8, strokeColor: '#ffffff', z: Z.OV_TEXT }))
  texts.push(txt(rating, 750, titleY, 100,
    { font: 'fot', color: FONT_COLOR, anchor: 'ld', stroke: 8, strokeColor: '#ffffff', z: Z.OV_TEXT }))

  if (!levelText) {
    ratingOverlay({ images, texts, rating, levelData, isLv15, layout, plan, statistics, playedMap })
  }

  const scale = levelText ? 1 : 0.8
  return {
    width: 1400,
    height: layout.height,
    scale,
    cssWidth: Math.trunc(1400 * scale),
    cssHeight: Math.trunc(layout.height * scale),
    pageLeft: 0,
    pageTop: 0,
    bgCss: tricolorGradientCss(),
    card: cardElement(layout.card),
    images,
    texts,
  }
}

/** 完成表叠加层（源 rating_table.py:185-315 全分支） */
function ratingOverlay({ images, texts, rating, levelData, isLv15, layout, plan, statistics, playedMap }) {
  const totalSongsCount = Object.values(levelData ?? {}).reduce((a, b) => a + b.length, 0)
  const achievementsOrFc = []

  // 源 im.alpha_composite(self._table_complete_bg, (251, 190))：垫在统计文字下（z=4 < 文字 5）
  images.push(img(picSrc('complete.png'), 251, 190, null, null, { z: Z.OV_ART }))

  // 首行「已通关数/总数」：源 tb.draw(394, 238, 30, ..., mm, stroke 5 白)
  texts.push(txt(`${statistics.clear}/${totalSongsCount}`, 394, RATING_GRID.statsFirstLineY, 30,
    { font: 'tb', color: DEFAULT_TEXT_COLOR, anchor: 'mm', stroke: 5, strokeColor: '#ffffff', z: Z.OV_TEXT }))
  // 其后 15 项：前 6 项 534+col*102 @238，其余 9 项 292+col*102 @323（源 STATISTICS_KEYS[1:] 遍历）
  const rest = STATISTICS_KEYS.slice(1)
  rest.forEach((key, n) => {
    const x = n < 6
      ? RATING_GRID.statsFirstLineX + (n % 6) * 102
      : RATING_GRID.statsSecondLineX + ((n - 6) % 9) * 102
    const y = n < 6 ? RATING_GRID.statsFirstLineY : RATING_GRID.statsSecondLineY
    texts.push(txt(statistics[key], x, y, 30,
      { font: 'tb', color: DEFAULT_TEXT_COLOR, anchor: 'mm', stroke: 2, strokeColor: '#ffffff', z: Z.OV_TEXT }))
  })

  // 逐格状态
  const cells = isLv15
    ? layout.cells.map(c => ({ song: c.song, x: c.x, y: c.y }))
    : layout.groups.flatMap(g => g.songs.map(c => ({ song: c.song, x: c.x, y: c.y })))

  for (const cell of cells) {
    if (!cell.song) continue
    const record = playedMap?.get(cell.song.song_id)?.get(cell.song.difficulties.level_index)
    if (!record) continue
    const ds = cell.song.difficulties.level_value

    if (!plan) {
      achievementsOrFc.push(record.achievements)
      // 源：≥100% 用 complete_1，否则 unfinished_1（半透明 maxA=179，必须压在底图曲 id 文字之上）
      images.push(img(picSrc(record.achievements >= 100 ? 'complete_1.png' : 'unfinished_1.png'),
        cell.x + 1, cell.y + 1, null, null, { z: Z.CELL }))
      // ⚠️ 不做 lower：图标文件名为展示名（UI_TTR_Rank_SSSp.png）
      const rate = computeRating(ds, record.achievements, { onlyrate: true })
      // lv15 大格用原生 256×120；其余 78×35（源两分支尺寸不同）
      if (isLv15) {
        images.push(img(themedPicSrc('prism_plus', `UI_TTR_Rank_${rate}.png`), cell.x + 55, cell.y + 115, null, null, { z: Z.CELL }))
      } else {
        images.push(img(themedPicSrc('prism_plus', `UI_TTR_Rank_${rate}.png`), cell.x, cell.y + 20, 78, 35, { z: Z.CELL }))
      }
      continue
    }

    if (record.fc) {
      achievementsOrFc.push(COMBO_SP.indexOf(record.fc))
      images.push(img(picSrc('complete_1.png'), cell.x + 1, cell.y + 1, null, null, { z: Z.CELL }))
      if (isLv15) {
        images.push(img(picSrc(`UI_CHR_PlayBonus_${COMBO_MAP[record.fc]}.png`), cell.x + 75, cell.y + 80, 200, 200, { z: Z.CELL }))
      } else {
        images.push(img(picSrc(`UI_MSS_MBase_Icon_${COMBO_MAP[record.fc]}.png`), cell.x + 15, cell.y + 13, 50, 50, { z: Z.CELL }))
      }
    }
  }

  // 全清徽章（源：仅当收集数等于该等级谱面总数时判定；-1 表示未达任何档位）
  if (achievementsOrFc.length === totalSongsCount) {
    const r = calcAchievementsFc(achievementsOrFc, totalSongsCount, plan)
    if (r !== -1) {
      const pic = plan ? COMBO_MAP[COMBO_SP[r]] : RANK_MAP[RANK_SP.slice(-6)[r]]
      images.push(img(picSrc(`UI_MSS_Allclear_Icon_${pic}.png`), 40, 40, null, null, { z: Z.CELL }))
    }
  }
}

export { RATING_GRID, DEFAULT_TEXT_COLOR }

// =====================================================================
// 版本称号完成表（源 core/image/plate_table.py:315 DrawPlateTable）
// =====================================================================

/** 源 plate_table.py:331 _get_plate_icon —— 达成图标的来源与尺寸随计划而变 */
function plateIcon(play, plan) {
  if (plan === '将' || plan === '者') {
    // ⚠️ 与统计侧不同，此处**不做 lower**（文件名就是 UI_TTR_Rank_SSS.png）
    const rate = computeRating(play.level_value, play.achievements, { onlyrate: true })
    return { src: themedPicSrc('prism_plus', `UI_TTR_Rank_${rate}.png`), w: 80, h: 36 }
  }
  const cfg = PLAN_CRITERIA[plan]
  const val = play[cfg.attr]
  const iconName = COMBO_MAP[val] ?? SYNC_MAP[val] ?? val
  return { src: picSrc(`${cfg.prefix}${iconName}.png`), w: 60, h: 60 }
}

/**
 * 版本称号完成表页面（源 plate_table.py:346 DrawPlateTable.draw）
 *
 * 底图仍是「本插件按源 update_table.py 坐标重画」（ADR-7），源坐标空间 1400 宽，**不做缩放**。
 * 底图取当前页的等级集合（舞-1/舞-2 各自成页），与源的 `plate_table/舞-{page}.png` 同构。
 *
 * @param {object} o
 * @param {string} o.version 短版本字（贴图路径用，源 _plate_background 亦用短字）
 * @param {string} o.versionName VERSION_MAP 版本名
 * @param {boolean} o.isWu
 * @param {number} o.page 1 基页码（仅舞）
 * @param {string} o.plan 称号字
 * @param {object} o.data processPlateTable 输出
 * @param {Set<number>} o.remasterIdSet 舞ReMASTER id 集
 * @param {string} o.botName
 */
export function plateTableView({
  version, isWu, page, plan, data, remasterIdSet = null, botName = '',
}) {
  // 底图只含当前页等级（源底图按页预生成），这样叠加层的 y 与底图网格逐格对齐
  const buckets = [...data.levels.entries()]
    .filter(([level]) => data.displaySet.has(level))
    .map(([level, rows]) => ({
      level,
      songs: rows.map(r => data.songsById.get(r.song_id)).filter(Boolean),
    }))
  const layout = plateTableLayout(buckets, { pages: isWu ? page - 1 : null, remasterIdSet })

  const images = tableBgLayers(layout.height, layout.separatorHeight)
  const texts = []
  // 底图网格（与 ratingBaseLayers 同构，但间距 96 / 曲绘 80 / 曲 id 字号 16）
  for (const g of layout.groups) {
    texts.push(txt(g.level, g.labelX, g.labelY, 40,
      { font: 'fot', color: FONT_COLOR, anchor: 'lm', stroke: 4, strokeColor: '#ffffff', z: Z.BASE_TEXT }))
    for (const cell of g.songs) {
      images.push(img(songChartSrc(cell.song.song_id), cell.x, cell.y, 80, 80, { z: Z.GRID_IMG }))
      // 白谱（舞ReMASTER）用另一套 id 底板与紫色字（源 _draw_plate）
      images.push(img(picSrc(cell.isRemaster ? 'border_table_remaster.png' : 'border_table_base.png'),
        cell.x - 5, cell.y - 5, null, null, { z: Z.GRID_IMG }))
      texts.push(txt(cell.song.song_id, cell.x + 56, cell.y + 4, 16,
        { font: 'tb', color: cell.isRemaster ? '#8a00e2' : '#ffffff', anchor: 'mm', z: Z.BASE_TEXT }))
    }
  }
  // 舞/霸者底图特有：源 update_table.py:_draw_plate 的 `Pages {n}/2`（仅 pages 非 None 时）
  if (layout.pagesText) {
    texts.push(txt(layout.pagesText.text, layout.pagesText.x, layout.pagesText.y, 40,
      { font: 'fot', color: FONT_COLOR, anchor: 'mm', z: Z.BASE_TEXT }))
  }
  texts.push(footerElement(layout.footer, botName))

  // ---- 叠加层：进度条 / 牌子徽章 / 统计 ----
  const progressBg = isWu ? 'plate_progress_wu.png' : 'plate_progress.png'
  images.push(img(picSrc(progressBg), 175, 20, null, null, { z: Z.OV_ART }))

  const plateArt = maiSrc('plate_version', `${version}${platePlanChar(plan)}.png`)
  // 源遇缺图抛 FileNotFoundError → @handle_errors 复刻为通用错误文案；
  // <img> 坏 src 只会画破图占位符，故此处主动抛错（R5）
  if (!fs.existsSync(picSrcToPath(plateArt))) {
    throw new Error(`plate_version art missing: ${version}${platePlanChar(plan)}.png`)
  }
  images.push(img(plateArt, 200, 45, 1000, 161, { z: Z.OV_ART }))

  const progressWidth = isWu ? 176 : 230
  const statsStartX = isWu ? 292 : 320
  const statsGapX = isWu ? 204 : 253
  const progressTextX = isWu ? 89 : 115
  const progressX = isWu ? 88 : 115

  for (const g of layout.groups) {
    for (const cell of g.songs) {
      const row = data.levels.get(g.level)?.find(r => r.song_id === cell.song.song_id)
      if (!row) continue
      const index = row.results.length - 1
      // 源：仅当「最高难度槽位」达标时才画大字图标
      if (row.qualified_slots.includes(index)) {
        images.push(img(picSrc('complete_2.png'), cell.x + 1, cell.y + 1, null, null, { z: Z.CELL }))
        const icon = plateIcon(row.results[index], plan)
        const dx = plan === '将' || plan === '者' ? 0 : 10
        const dy = plan === '将' || plan === '者' ? 22 : 12
        images.push(img(icon.src, cell.x + dx, cell.y + dy, icon.w, icon.h, { z: Z.CELL }))
      }
      for (const sIdx of row.qualified_slots) {
        if (isWu && row.results.length === 5) {
          images.push(img(picSrc(`t_${sIdx}.png`), cell.x + 1 + 16 * sIdx, cell.y + 64, 14, 14, { z: Z.CELL }))
        } else {
          images.push(img(picSrc(`t_${sIdx}.png`), cell.x + 4 + 19 * sIdx, cell.y + 63, null, null, { z: Z.CELL }))
        }
      }
    }
  }

  const completeSum = data.completedCount
  const total = data.totalCount
  const text = completeSum === total ? 'COMPLETED!!!' : `${completeSum}/${total}`
  const progress = total === 0 ? 0 : completeSum / total
  if (progress !== 0) {
    images.push(img(picSrc('progress_big.png'), 204, 219, Math.trunc(993 * progress), 92,
      { crop: true, z: Z.OV_ART }))
  }
  texts.push(txt(text, 700, 240, 30,
    { font: 'fot', color: DEFAULT_TEXT_COLOR, anchor: 'mm', stroke: 3, strokeColor: '#ffffff', z: Z.OV_TEXT }))
  texts.push(txt(`${pyRound2(progress * 100)}%`, 1190, 240, 30,
    { font: 'fot', color: DEFAULT_TEXT_COLOR, anchor: 'rm', stroke: 3, strokeColor: '#ffffff', z: Z.OV_TEXT }))

  data.slotCounts.forEach((completeSumGroup, l) => {
    const x = statsStartX + l * statsGapX
    const plateCount = l !== 4 ? total : data.remasterCount
    if (!plateCount) return
    const progressGroup = completeSumGroup / plateCount
    if (progressGroup !== 0) {
      images.push(img(picSrc(isWu ? 'progress_small_wu.png' : 'progress_small.png'),
        x - progressX, 326, Math.trunc(progressWidth * progressGroup), 46, { crop: true, z: Z.OV_ART }))
    }
    texts.push(txt(completeSumGroup, x, 300, 40,
      { font: 'fot', color: ID_TEXT_COLOR[l], anchor: 'mm', stroke: 4, strokeColor: '#ffffff', z: Z.OV_TEXT }))
    texts.push(txt(`/${plateCount}`, x + progressTextX, 320, 14,
      { font: 'fot', color: ID_TEXT_COLOR[l], anchor: 'rd', stroke: 3, strokeColor: '#ffffff', z: Z.OV_TEXT }))
    texts.push(txt(`${pyRound2(progressGroup * 100)}%`, x + progressTextX, 343, 20,
      { font: 'fot', color: DEFAULT_TEXT_COLOR, anchor: 'rm', stroke: 2, strokeColor: '#ffffff', z: Z.OV_TEXT }))
  })

  return {
    width: 1400,
    height: layout.height,
    scale: 1,
    cssWidth: 1400,
    cssHeight: layout.height,
    pageLeft: 0,
    pageTop: 0,
    bgCss: tricolorGradientCss(),
    card: cardElement(layout.card),
    images,
    texts,
  }
}

/** 源 _plate_background 的称号字归一：'极' → '極'（磁盘文件名用繁体） */
function platePlanChar(plan) {
  return plan === '极' ? '極' : plan
}

/** file:// URL → 本地路径（仅用于存在性预检） */
function picSrcToPath(url) {
  return decodeURIComponent(url.replace(/^file:\/\/\//, ''))
}
